### PR TITLE
Added missing dependencies

### PR DESCRIPTION
**Pull request by tamersaadeh**

### CODE REVIEW

**Comment by markstory** [comment]
Thanks for fixing this, I forgot to update the dependencies as the collected.

**Comment by tamersaadeh** [comment]
No problem. The only thing is that I seem to be unable to use it with gmail, which is the only way for me to test it and play with it.

**Comment by markstory** [comment]
Hmm, I'll take a look.  So far I've only put it on my job's internal jabber network.  I'll take a look at gmail jabber though.

**Comment by tamersaadeh** [comment]
I mean the only _real_ issue with gmail is that there is not _rooms_.

**Pull request merged**
